nameOverride: ""
fullnameOverride: ""

global:
  namespace: naavre

  # WARNING: don't verify SSL certificates (don't use in production!)
  insecureSkipVerifySSL: false

  ingress:
    domain: example.org
    seaweedfsS3Domain: s3.example.org
    commonAnnotations: {}
    tls:
      enabled: false
    redirectDomainToPaasFrontend: false

  secrets:
    k8sSecretCreator:
      apiToken:
    keycloak:
      adminPassword:
      naavreClientSecret:
      users: []
      postgresql:
        # database and username match the values set by the bitnami/keycloak
        # helm chart, so that the pv can be reused when migrating from the
        # bitnami helm chart to the official operator
        database: bitnami_keycloak
        username: bn_keycloak
        password:
    seaweedfs:
      catalogueBucket:
        access_key:
        secret_key:
    naavreCatalogueService:
      secretKey:
      auth:
        superuser:
          email: "admin@example.org"
          username: admin
          password:
      postgresql:
        password:
    naavrePaasFrontend:
      secretKey:

  common:
    velero:
      podAnnotations:
        backup.velero.io/backup-volumes: pvc-volume,emptydir-volume
    corePods:
      affinity: {}
    userPods:
      # See documentation README.md#add-minio-mount-to-user-containers
      extraVolumeMounts: []
        # - name: my-pvc
        #   mountPath: /path/to/my-mount-point
        #   readOnly: true  # optional
        #   subPath: 'path/in/pv'  # optional
        #   allowedGroups: ['example_group']  # optional

  externalServices:
    argoWorkflows:
      useExternal: false
      namespace: nil
      url: nil
      token: nil
      executor_service_account: nil
    k8sSecretCreator:
      useExternal: false
      url: nil
      token: nil
    keycloak:
      useExternal: false
      url: nil
      realm: nil
      client_id: nil
      client_secret: nil
    s3:
      # Use an external S3-compatible object storage in replacement of the local seaweedfs.
      useExternal: false
      catalogueBucket:
        # S3-compatible object storage configuration.
        # The key should grant permission for:
        # s3:GetObject, s3:PutObject, s3:DeleteObject, and s3:ListBucket on
        # `arn:aws:s3:::example-bucket-name/*` and `arn:aws:s3:::example-bucket-name`
        endpoint_url: nil
        bucket_name: nil
        access_key: nil
        secret_key: nil

argoWorkflows:
  enabled: true
  workflowTTL: 86400
  crds:
    install: true
  ingress:
    basePath: /argowf

jupyterhub:
  enabled: true
  ingress:
    basePath: /jupyter
  scheduling:
    userPods:
      nodeAffinity:
        matchNodePurpose: prefer
  hub:
    concurrentSpawnLimit: 10
    consecutiveFailureLimit: 16
    activeServerLimit: 16
    namedServerLimitPerUser: 1
    extraConfig: {}
    initContainers: []
    extraVolumes: []
    extraVolumeMounts: []
  singleuser:
    memory:
      limit: 4G
      guarantee: 4G
    cpu:
      limit: 1.25
      guarantee: 1.1
    storage:
      capacity: 10Gi
      dynamic: {}

  communities: {}
  # myCommunity:
  #   title: My community

  vlabLabels: {}
  # myLabel:
  #   title: My label
  #   color: "#3c8f49"

  vlabs:
    openlab:
      enabled: true
      slug: openlab
      title: "NaaVRE Open Lab"
      communities: []
      # communities: [myCommunity]
      labels: []
      # labels: [myLabel]
      description: "Open experimentation with virtual labs"
      dirname: "Open Lab"
      # Optional icon (URL or base64 data: "data:image/svg+xml;base64,[...]")
      # icon:
      image:
        name: ghcr.io/naavre/flavors/naavre-fl-vanilla-jupyter
        tag: v0.3.6
      configuration:
        base_image_tags_url: https://github.com/NaaVRE/flavors/releases/download/v0.3.6/base_image_tags.json
        module_mapping_url: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
        cell_github_url:
        cell_github_token:
        registry_url:
        # Optional token to pull images from private registries (leave out for public ones)
        # registry_token: "<username>:<token>"
        log_queries: true
        splitter_max_branches: 32
        git_public: {}
          # Public git repo cloned when starting the lab
          # repo: https://example.org/my/repo.git
          # branch: main
        #
        # Optional file to open by default when starting the virtual lab (relative to /home/jovyan/)
        # default_file_path: Virtual Labs/Open Lab/Git public/tutorial/Your first workflow in Python.ipynb
        #
        # Optional workflow engine override for the virtual lab. Allows
        # configuring an external Argo workflows instance and
        # k8s-secrets-creator to be used for the current virtual lab only. If
        # unset, the default Argo workflows and k8s-secrets-creator are used
        # (this can be the ones deployed by the current charts or external ones
        # configured in global.externalServices)
        workflowEngineOverride: {}
          # argoWorkflows:
          #   namespace: nil
          #   url: nil
          #   token: nil
          #   executor_service_account: nil
          # k8sSecretCreator:
          #   url: nil
          #   token: nil
      postStartShSnippet: |
        echo "Do something"

k8sSecretCreator:
  enabled: true
  ingress:
    basePath: /k8s-secret-creator

keycloak:
  enabled: true
  image: quay.io/keycloak/keycloak:26.4.2
  ingress:
    basePath: /auth

seaweedfs:
  enabled: true
  catalogueBucket:
    bucket_name: naavre-catalogue

naavreCatalogueService:
  enabled: true
  ingress:
    basePath: /naavre-catalogue-service
  conf:
    dev_mode: false

naavreContainerizerService:
  enabled: true
  ingress:
    basePath: /naavre-containerizer-service

naavreWorkflowService:
  enabled: true
  ingress:
    basePath: /naavre-workflow-service

naavrePaasFrontend:
  enabled: true
